[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "nginx"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php-fpm -y /app/php-fpm.conf & nginx -c /app/nginx.conf"